

services:
  app:
    image: mini-tw-backend
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=mini-twitter-backend
    env_file:
      - .env
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
